---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: CI
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp: [24, 25]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: 3.20.0
      - run: |
          docker compose -f .ci/docker-compose.yml up -d --wait
          sleep 10
          docker exec mysql mysql -uroot -e "CREATE USER otptest@'%' IDENTIFIED BY 'otptest';"
          docker exec mysql mysql -uroot -e "GRANT ALL PRIVILEGES ON otptest.* TO otptest@'%';"
          docker exec mysql mysql -uroot -e "CREATE USER otptest2@'%' IDENTIFIED BY 'otptest2';"
          docker exec mysql mysql -uroot -e "GRANT ALL PRIVILEGES ON otptest.* TO otptest2@'%';"
          docker exec mysql-ssl mysql -uroot -e "CREATE USER otptestssl@'%' IDENTIFIED BY 'otptestssl' REQUIRE SSL;"
          docker exec mysql-ssl mysql -uroot -e "GRANT ALL PRIVILEGES ON otptest.* TO otptestssl@'%';"
      - run: make tests
